### ISSUE TITLE
Asking for Permission

### ISSUE THREAD

**Issue by mariosffx** [hugomn/hugo.im#3]
Hello!
I hope this is the best way to contact you.

Can I please have  permission to use this repositoritory to make my own personal portofolio?

I've been looking for a cool gatsby starter with int18n and yours is very cool.

PS) Of course I'm going to customize my own, add more features, upgrades, my own language, SEO (and whatever comes to my mind)

Thanks a bunch for your time.

**Comment by hugomn** [comment]
Hi @mariosffx! Thanks for opening the issue. And of course, it's a great pleasure to be able to contribute somehow. Please feel free to fork it and use it as you wish. I was planning to create a gastby theme for websites like this, with more of a "medium" blog section, but didn't have time yet, to be honest. If you have any feedback or improvements on the code, please let me know! ;)

**Comment by mariosffx** [comment]
Thanks, a lot!
I'll be opening issues then, 
Right now I'm just clearing warnings about propTypes. 
No big deal.
